BlogCore/Areas/Admin/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogCore.DataAccess.Data.Repository;
using BlogCore.Models;
using BlogCore.Models.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class ArticleController : Controller
    {
        private readonly IWorkContainer _workContainer;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ArticleController(IWorkContainer workContainer,IWebHostEnvironment webHostEnvironment)
        {
            _workContainer = workContainer;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            ArticleVM articleVM = new ArticleVM
            {
                Article = new Article(),
                ListCategory = _workContainer.category.getListCategory()

            };
            return View(articleVM);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ArticleVM articleVM = new ArticleVM
            {
                Article = new Article(),
                ListCategory = _workContainer.category.getListCategory()
            };

            if (id != null)
            {
                articleVM.Article = _workContainer.article.Get(id);
            }

            return View(articleVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArticleVM articleVM)
        {
            if (ModelState.IsValid)
            {

                Article art = _workContainer.article.Get(articleVM.Article.Id);

                string mainRoute = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (files.Count() > 0)
                {
                    // Editar imagen
                    string fileName = Guid.NewGuid().ToString();
                    string Uploads = Path.Combine(mainRoute, @"images\articles");
                    string extension = Path.GetExtension(files[0].FileName);

                    //Eliminar imagen 
                    string imageOld = Path.Combine(mainRoute, art.UrlImage.TrimStart('\\'));
                    if (System.IO.File.Exists(imageOld))
                    {
                        System.IO.File.Delete(imageOld);
                    }

                    // Subir nuevament la imagen
                    using (FileStream fs = new FileStream(Path.Combine(Uploads, $"{fileName}{extension}"), FileMode.Create))
                    {
                        files[0].CopyTo(fs);
                    };

                    articleVM.Article.UrlImage = @$"\images\articles\{fileName}{extension}";  
                }
                _workContainer.article.update(articleVM.Article);
                _workContainer.save();

                return RedirectToAction(nameof(Index));       
            }

            return View();

        }

        public IActionResult Create()
        {       
            ArticleVM articleVM = new ArticleVM
            {
                Article = new Article(),
                ListCategory = _workContainer.category.getListCategory()

            };
            return View(articleVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticleVM articleVM)
        {
            if (ModelState.IsValid)
            {
                string mainRoute = _webHostEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (articleVM.Article.Id == 0) 
                {
                    // Creación de Nuevo Articulo
                    string fileName = Guid.NewGuid().ToString();
                    string Uploads = Path.Combine(mainRoute, @"images\articles");
                    string extension = Path.GetExtension(files[0].FileName);

                    using (FileStream fs = new FileStream(Path.Combine(Uploads, $"{fileName}{extension}"),FileMode.Create))
                    {
                        files[0].CopyTo(fs);
                    };

                    articleVM.Article.UrlImage = @$"\images\articles\{fileName}{extension}";
                    _workContainer.article.add(articleVM.Article);
                    _workContainer.save();

                    return RedirectToAction(nameof(Index));
                }
            }

            return View();

        }

        //Seccion de apis

        public IActionResult GetAll()
        {
            return Json(new { data = _workContainer.article.GetAll(includeProperties:"category") });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Article article = _workContainer.article.Get(id);

            string mainRoute = _webHostEnvironment.WebRootPath;

            if (article.UrlImage != null)
            {
                string imageOld = Path.Combine(mainRoute, article.UrlImage.TrimStart('\\'));
                if (System.IO.File.Exists(imageOld))
                {
                    System.IO.File.Delete(imageOld);
                };
            };

            _workContainer.article.Remove(article);
            _workContainer.save();

            return Json(new { success = true, message = "El articulo fue borrado" });

        }



    }
}

BlogCore/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogCore.DataAccess.Data.Repository;
using BlogCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IWorkContainer _workContainer;

        public CategoryController(IWorkContainer workContainer)
        {
            _workContainer = workContainer;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Category category = new Category();
            category = _workContainer.category.Get(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _workContainer.category.add(category);
                _workContainer.save();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _workContainer.category.update(category);
                _workContainer.save();
                return RedirectToAction(nameof(Index));
            }

            return View(category);

        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Category category = _workContainer.category.Get(id);
            if (category == null)
            {
                return Json(new { success = false, message = "Error al eliminar categoria" });
            }

            _workContainer.category.Remove(category);
            _workContainer.save();

            return Json(new { success = true, message = "Categoria borrada correctamente" });

        }

        #region Llmadas a las apis

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _workContainer.category.GetAll() });
        }



        #endregion

    }
}

BlogCore/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BlogCore.DataAccess.Data;
using BlogCore.DataAccess.Data.Repository;
using BlogCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class SliderController : Controller
    {

        private readonly IWorkContainer _workContainer;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SliderController(IWorkContainer workContainer,IWebHostEnvironment webHostEnvironment)
        {
            _workContainer = workContainer;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Slider slider =  _workContainer.slider.Get(id);
            if (slider == null)
            {
                return NotFound();
            }

            return View(slider);
        }


        // Lamada a las apis 
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json( new { data = _workContainer.slider.GetAll() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider slider)
        {
            var files = HttpContext.Request.Form.Files;

            if (files.Count() > 0)
            {
                string mainRoute = _webHostEnvironment.WebRootPath;
                string fileName = Guid.NewGuid().ToString();
                string Uploads = Path.Combine(mainRoute, @"images\sliders");
                string extension = Path.GetExtension(files[0].FileName);

                using (FileStream fs = new FileStream(Path.Combine(Uploads, $"{fileName}{extension}"), FileMode.Create))
                {
                    files[0].CopyTo(fs);
                };

                slider.UrlImage = @$"\images\sliders\{fileName}{extension}";
                ModelState["UrlImage"].ValidationState = ModelValidationState.Valid;
            }
            else
            {
                slider.UrlImage = null;
            }

            if (ModelState.IsValid)
            {
                _workContainer.slider.add(slider);
                _workContainer.save();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider slider)
        {
            var files = HttpContext.Request.Form.Files;

            if (files.Count() > 0)
            {
                string mainRoute = _webHostEnvironment.WebRootPath;
                string fileName = Guid.NewGuid().ToString();
                string Uploads = Path.Combine(mainRoute, @"images\sliders");
                string extension = Path.GetExtension(files[0].FileName);

                using (FileStream fs = new FileStream(Path.Combine(Uploads, $"{fileName}{extension}"), FileMode.Create))
                {
                    files[0].CopyTo(fs);
                };

                //Eliminar imagen 
                string imageOld = Path.Combine(mainRoute, slider.UrlImage.TrimStart('\\'));
                if (System.IO.File.Exists(imageOld))
                {
                    System.IO.File.Delete(imageOld);
                }

                slider.UrlImage = @$"\images\sliders\{fileName}{extension}";
            }

            if (ModelState.IsValid)
            {
                _workContainer.slider.update(slider);
                _workContainer.save();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }


        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Slider slider = _workContainer.slider.Get(id);

            if (slider == null)
            {
                return Json(new { success = false, message = "Error al eliminar registro" });
            }

            _workContainer.slider.Remove(id);
            _workContainer.save();

            return Json(new { success = true, message = "registro borrado" });

        }

    }
}

BlogCore/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BlogCore.DataAccess.Data.Repository;
using BlogCore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlogCore.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly IWorkContainer _workContainer;

        public UserController(IWorkContainer workContainer)
        {
            _workContainer = workContainer;
        }

        public IActionResult Index()
        {
            var claimsUser = (ClaimsIdentity)this.User.Identity;
            var currentUser = claimsUser.FindFirst(ClaimTypes.NameIdentifier);
            return View(_workContainer.applicationUser.GetAll(u => u.Id != currentUser.Value));
        }

        public IActionResult Block(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _workContainer.applicationUser.BlockUser(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Unlock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            _workContainer.applicationUser.UnlockUser(id);
            return RedirectToAction(nameof(Index));
        }



    }
}

BlogCore/Views/Shared/_Layout.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!--Css todos-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" asp-area="Client" asp-controller="Home" asp-action="Index">Blog Core</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    @if (User.IsInRole(BlogCore.Utilities.Cnt.Admin))
                    {
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-white" id="navbarDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Contenidos
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropDown">
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categorias</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Article" asp-action="Index">Articulos</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="Slider" asp-action="Index">Sliders</a>
                            <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Usuarios</a>
                        </div>
                    </li>
                    }
                    
                </ul>
            </div>
            @await Html.PartialAsync("_LoginPartial.cshtml")
        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3 pt-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BlogCore/Views/Shared/_ViewCreateBack.cshtml
<div class="row">
    <div class="col" >
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
     <div class="col" >
        <a asp-action="Index" class="btn btn-success form-control">Rgresar al inicio</a>
    </div>
</div>